name: minio
version: master
summary: Open source object storage server compatible with Amazon S3 APIs
description: |
  Minio is an object storage server released under Apache License v2.0. It is
  compatible with Amazon S3 cloud storage service. It is best suited for
  storing unstructured data such as photos, videos, log files, backups and
  container / VM images. Size of an object can range from a few KBs to a
  maximum of 5TB.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  minio:
    command: minio
    plugs:
      - home
      - mount-observe
      - network
      - network-bind
      - removable-media

parts:
  minio:
    source: .
    plugin: go
    go-importpath: github.com/pydio/minio-priv
    after: [go]
  go:
    source-tag: go1.8.3
